DROP TABLE IF EXISTS stores CASCADE;
CREATE TABLE stores (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR (255),
  google_place_id VARCHAR(255),
  type VARCHAR(255) NOT NULL,
  lat DECIMAL NOT NULL,
  lng DECIMAL NOT NULL
);